jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersmanagement?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true #change this to your database url
    password: root #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false